server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compression
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    # Assets avec cache long terme (Angular hash dans le nom de fichier)
    location ~* \.(js|css|woff2?|ttf|eot|svg|ico|png|jpg|gif)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback : toutes les routes Angular → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
